### ISSUE TITLE
Spec creates unpacked files (and with wrong dir perms)

### ISSUE THREAD

**Issue by luizluca** [OpenNMS/jrrd2#5]
Hello,

This part of spec is simply useless:

```
install -d -m 655 ${RPM_BUILD_ROOT}%{_datadir}/javadoc/%{name}
unzip -d ${RPM_BUILD_ROOT}%{_datadir}/javadoc/%{name} dist/jrrd2*javadoc*.jar

```
Permission 655 will result in error. It should be 755. Anyway, those files are not packed into any subpackages.

**Comment by luizluca** [comment]
They does not get into any package because of the wrong perm. Fixing this take them into -devel

**Comment by RangerRick** [comment]
Could have sworn I already fixed the perm issue but apparently not.  :/
